### ISSUE TITLE
[Bug] Error when modpack name contains invalid Win32 path characters

### ISSUE THREAD

**Issue by yoyokenny** [bhopahk/launcher#4]
**Describe the bug**
When either a profile is created or when a modpack is installed, if the instance name contains invalid Win32 path characters there is an error.

**To Reproduce**
Steps to reproduce the behavior, please include screenshots where possible:
1. Create/install any profile/modpack that contains invalid Win32 path characters.

**Operating System:**
Windows 7 x64 Pro

**Notes:**
Sanitising the instance name before adding it to the instance path should fix this bug.

For convenience, I believe the best place to do the sanitise would be [here](https://github.com/bhopahk/launcher/blob/ba23d6c5c93236997209c11411dbe78bcfbbd57c/src/main/app/profile.js#L139)

**Comment by bhopahk** [comment]
This is fixed in 0.3.4.

I decided to sanitize the [name](https://github.com/bhopahk/launcher/blob/master/src/main/app/profile.js#L136) instead which will make it so any invalid file path characters will be removed. 

Currently the name is resolved by checking for existing directories (to allow profiles with the same name (`name (1)`) meaning that if I sanitize just directory name, two profiles could have the same directory. In the future I would like to stop using directory names to catch duplicates and at that point I will likely switch to just sanitizing the directory name, not the display name.

Thanks for the report by the way :)

**Comment by yoyokenny** [comment]
Cheers, loving the launcher so far :)
